package catalog

// messierCatalog contains all 110 Messier objects with J2000 coordinates,
// cross-references, and descriptive metadata sourced from SEDS Messier
// database and standard astronomical references.
var messierCatalog = []CelestialObject{
	{
		Name:          "Crab Nebula",
		CatalogID:     "M1",
		AlternateIDs:  []string{"NGC 1952"},
		Type:          ObjectTypeSupernovaRem,
		RAJ2000:       5.5755,
		DecJ2000:      22.0145,
		Magnitude:     8.4,
		AngularSize:   7.0,
		Constellation: "Tau",
		Description:   "Supernova remnant from SN 1054; pulsar-powered synchrotron nebula",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M2",
		AlternateIDs:  []string{"NGC 7089"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       21.5578,
		DecJ2000:      -0.8233,
		Magnitude:     6.5,
		AngularSize:   16.0,
		Constellation: "Aqr",
		Description:   "Rich, highly compressed globular cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M3",
		AlternateIDs:  []string{"NGC 5272"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       13.7028,
		DecJ2000:      28.3767,
		Magnitude:     6.2,
		AngularSize:   18.0,
		Constellation: "CVn",
		Description:   "One of the largest and brightest globular clusters; ~500,000 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M4",
		AlternateIDs:  []string{"NGC 6121"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       16.3933,
		DecJ2000:      -26.5258,
		Magnitude:     5.9,
		AngularSize:   26.3,
		Constellation: "Sco",
		Description:   "Nearest globular cluster; prominent central bar of stars",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M5",
		AlternateIDs:  []string{"NGC 5904"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       15.3097,
		DecJ2000:      2.0808,
		Magnitude:     5.8,
		AngularSize:   23.0,
		Constellation: "Ser",
		Description:   "Ancient globular cluster, estimated age ~13 Gyr",
		CatalogSource: "messier",
	},
	{
		Name:          "Butterfly Cluster",
		CatalogID:     "M6",
		AlternateIDs:  []string{"NGC 6405"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       17.6678,
		DecJ2000:      -32.2167,
		Magnitude:     4.2,
		AngularSize:   25.0,
		Constellation: "Sco",
		Description:   "Open cluster with a butterfly-shaped outline; ~80 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "Ptolemy Cluster",
		CatalogID:     "M7",
		AlternateIDs:  []string{"NGC 6475"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       17.8978,
		DecJ2000:      -34.8333,
		Magnitude:     3.3,
		AngularSize:   80.0,
		Constellation: "Sco",
		Description:   "Bright, large open cluster visible to naked eye; recorded by Ptolemy in 130 AD",
		CatalogSource: "messier",
	},
	{
		Name:          "Lagoon Nebula",
		CatalogID:     "M8",
		AlternateIDs:  []string{"NGC 6523"},
		Type:          ObjectTypeNebula,
		RAJ2000:       18.0622,
		DecJ2000:      -24.3833,
		Magnitude:     5.8,
		AngularSize:   90.0,
		Constellation: "Sgr",
		Description:   "Large emission nebula with embedded open cluster NGC 6530",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M9",
		AlternateIDs:  []string{"NGC 6333"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       17.3194,
		DecJ2000:      -18.5158,
		Magnitude:     7.9,
		AngularSize:   9.3,
		Constellation: "Oph",
		Description:   "Globular cluster near the galactic center",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M10",
		AlternateIDs:  []string{"NGC 6254"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       16.9522,
		DecJ2000:      -4.1003,
		Magnitude:     6.6,
		AngularSize:   15.1,
		Constellation: "Oph",
		Description:   "Bright globular cluster with a loose core",
		CatalogSource: "messier",
	},
	{
		Name:          "Wild Duck Cluster",
		CatalogID:     "M11",
		AlternateIDs:  []string{"NGC 6705"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       18.8511,
		DecJ2000:      -6.2667,
		Magnitude:     6.3,
		AngularSize:   14.0,
		Constellation: "Sct",
		Description:   "Very rich and compact open cluster; ~2900 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M12",
		AlternateIDs:  []string{"NGC 6218"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       16.7872,
		DecJ2000:      -1.9483,
		Magnitude:     6.7,
		AngularSize:   16.0,
		Constellation: "Oph",
		Description:   "Loosely concentrated globular cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M13",
		AlternateIDs:  []string{"NGC 6205"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       16.6947,
		DecJ2000:      36.4608,
		Magnitude:     5.8,
		AngularSize:   20.0,
		Constellation: "Her",
		Description:   "Great Hercules Globular Cluster; ~300,000 stars; target of 1974 Arecibo message",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M14",
		AlternateIDs:  []string{"NGC 6402"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       17.6261,
		DecJ2000:      -3.2458,
		Magnitude:     7.6,
		AngularSize:   11.7,
		Constellation: "Oph",
		Description:   "Intermediate-richness globular cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M15",
		AlternateIDs:  []string{"NGC 7078"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       21.4997,
		DecJ2000:      12.1670,
		Magnitude:     6.4,
		AngularSize:   18.0,
		Constellation: "Peg",
		Description:   "One of the densest known globular clusters; contains planetary nebula Pease 1",
		CatalogSource: "messier",
	},
	{
		Name:          "Eagle Nebula",
		CatalogID:     "M16",
		AlternateIDs:  []string{"NGC 6611"},
		Type:          ObjectTypeNebula,
		RAJ2000:       18.3131,
		DecJ2000:      -13.7833,
		Magnitude:     6.4,
		AngularSize:   7.0,
		Constellation: "Ser",
		Description:   "Emission nebula with young open cluster; contains Pillars of Creation",
		CatalogSource: "messier",
	},
	{
		Name:          "Omega Nebula",
		CatalogID:     "M17",
		AlternateIDs:  []string{"NGC 6618"},
		Type:          ObjectTypeNebula,
		RAJ2000:       18.3469,
		DecJ2000:      -16.1833,
		Magnitude:     6.0,
		AngularSize:   46.0,
		Constellation: "Sgr",
		Description:   "Swan or Horseshoe Nebula; one of the brightest emission nebulae",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M18",
		AlternateIDs:  []string{"NGC 6613"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       18.3322,
		DecJ2000:      -17.1333,
		Magnitude:     7.5,
		AngularSize:   9.0,
		Constellation: "Sgr",
		Description:   "Sparse open cluster with about 20 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M19",
		AlternateIDs:  []string{"NGC 6273"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       17.0439,
		DecJ2000:      -26.2667,
		Magnitude:     7.2,
		AngularSize:   17.0,
		Constellation: "Oph",
		Description:   "One of the most oblate globular clusters known",
		CatalogSource: "messier",
	},
	{
		Name:          "Trifid Nebula",
		CatalogID:     "M20",
		AlternateIDs:  []string{"NGC 6514"},
		Type:          ObjectTypeNebula,
		RAJ2000:       18.0431,
		DecJ2000:      -23.0333,
		Magnitude:     8.5,
		AngularSize:   28.0,
		Constellation: "Sgr",
		Description:   "Emission, reflection, and dark nebula divided into three lobes by dust lanes",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M21",
		AlternateIDs:  []string{"NGC 6531"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       18.0756,
		DecJ2000:      -22.5000,
		Magnitude:     6.5,
		AngularSize:   13.0,
		Constellation: "Sgr",
		Description:   "Open cluster near the Trifid Nebula",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M22",
		AlternateIDs:  []string{"NGC 6656"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       18.6061,
		DecJ2000:      -23.9047,
		Magnitude:     5.1,
		AngularSize:   32.0,
		Constellation: "Sgr",
		Description:   "One of the brightest globular clusters; among the first to be discovered",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M23",
		AlternateIDs:  []string{"NGC 6494"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       17.9489,
		DecJ2000:      -18.9833,
		Magnitude:     6.9,
		AngularSize:   27.0,
		Constellation: "Sgr",
		Description:   "Rich open cluster of about 150 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M24",
		AlternateIDs:  []string{"IC 4715"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       18.2833,
		DecJ2000:      -18.5667,
		Magnitude:     4.6,
		AngularSize:   90.0,
		Constellation: "Sgr",
		Description:   "Sagittarius Star Cloud; a dense star-field window through the Milky Way",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M25",
		AlternateIDs:  []string{"IC 4725"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       18.5267,
		DecJ2000:      -19.1167,
		Magnitude:     4.6,
		AngularSize:   32.0,
		Constellation: "Sgr",
		Description:   "Large, bright open cluster containing Cepheid variable U Sgr",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M26",
		AlternateIDs:  []string{"NGC 6694"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       18.7547,
		DecJ2000:      -9.4000,
		Magnitude:     8.0,
		AngularSize:   15.0,
		Constellation: "Sct",
		Description:   "Open cluster with a central star-poor region",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M27",
		AlternateIDs:  []string{"NGC 6853"},
		Type:          ObjectTypePlanetaryNeb,
		RAJ2000:       19.9936,
		DecJ2000:      22.7211,
		Magnitude:     7.5,
		AngularSize:   8.0,
		Constellation: "Vul",
		Description:   "Dumbbell Nebula; first planetary nebula to be discovered (1764)",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M28",
		AlternateIDs:  []string{"NGC 6626"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       18.4086,
		DecJ2000:      -24.8700,
		Magnitude:     6.9,
		AngularSize:   11.2,
		Constellation: "Sgr",
		Description:   "Compact globular cluster; contains millisecond pulsar PSR B1821-24",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M29",
		AlternateIDs:  []string{"NGC 6913"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       20.3936,
		DecJ2000:      38.5167,
		Magnitude:     7.1,
		AngularSize:   7.0,
		Constellation: "Cyg",
		Description:   "Small, young open cluster of about 50 stars in Cygnus",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M30",
		AlternateIDs:  []string{"NGC 7099"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       21.6728,
		DecJ2000:      -23.1800,
		Magnitude:     7.7,
		AngularSize:   12.0,
		Constellation: "Cap",
		Description:   "Globular cluster with core collapse; dramatic central concentration",
		CatalogSource: "messier",
	},
	{
		Name:          "Andromeda Galaxy",
		CatalogID:     "M31",
		AlternateIDs:  []string{"NGC 224"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       0.7122,
		DecJ2000:      41.2692,
		Magnitude:     3.4,
		AngularSize:   190.0,
		Constellation: "And",
		Description:   "Nearest major galaxy to the Milky Way; spiral galaxy ~2.537 Mly away",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M32",
		AlternateIDs:  []string{"NGC 221"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       0.7117,
		DecJ2000:      40.8650,
		Magnitude:     8.7,
		AngularSize:   8.7,
		Constellation: "And",
		Description:   "Compact elliptical satellite galaxy of M31",
		CatalogSource: "messier",
	},
	{
		Name:          "Triangulum Galaxy",
		CatalogID:     "M33",
		AlternateIDs:  []string{"NGC 598"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       1.5642,
		DecJ2000:      30.6600,
		Magnitude:     5.7,
		AngularSize:   70.8,
		Constellation: "Tri",
		Description:   "Spiral galaxy; third-largest in Local Group; low surface brightness",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M34",
		AlternateIDs:  []string{"NGC 1039"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       2.7019,
		DecJ2000:      42.7667,
		Magnitude:     5.5,
		AngularSize:   35.0,
		Constellation: "Per",
		Description:   "Bright open cluster of about 100 stars; easily resolved",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M35",
		AlternateIDs:  []string{"NGC 2168"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       6.1481,
		DecJ2000:      24.3333,
		Magnitude:     5.3,
		AngularSize:   28.0,
		Constellation: "Gem",
		Description:   "Large, rich open cluster; background cluster NGC 2158 visible nearby",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M36",
		AlternateIDs:  []string{"NGC 1960"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       5.6039,
		DecJ2000:      34.1333,
		Magnitude:     6.3,
		AngularSize:   12.0,
		Constellation: "Aur",
		Description:   "Young open cluster in Auriga; contains many hot blue-white stars",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M37",
		AlternateIDs:  []string{"NGC 2099"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       5.8717,
		DecJ2000:      32.5500,
		Magnitude:     6.2,
		AngularSize:   24.0,
		Constellation: "Aur",
		Description:   "Richest of the three Auriga clusters; ~500 stars including red giants",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M38",
		AlternateIDs:  []string{"NGC 1912"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       5.4783,
		DecJ2000:      35.8333,
		Magnitude:     7.4,
		AngularSize:   21.0,
		Constellation: "Aur",
		Description:   "Open cluster forming a cross or pi pattern; ~100 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "Virgo Cluster Core",
		CatalogID:     "M49",
		AlternateIDs:  []string{"NGC 4472"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.4964,
		DecJ2000:      8.0003,
		Magnitude:     8.4,
		AngularSize:   10.2,
		Constellation: "Vir",
		Description:   "Brightest galaxy in the Virgo Cluster; giant elliptical",
		CatalogSource: "messier",
	},
	{
		Name:          "Bode's Galaxy",
		CatalogID:     "M81",
		AlternateIDs:  []string{"NGC 3031"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       9.9258,
		DecJ2000:      69.0653,
		Magnitude:     6.9,
		AngularSize:   26.9,
		Constellation: "UMa",
		Description:   "Grand design spiral galaxy; brightest member of the M81 Group",
		CatalogSource: "messier",
	},
	{
		Name:          "Cigar Galaxy",
		CatalogID:     "M82",
		AlternateIDs:  []string{"NGC 3034"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       9.9258,
		DecJ2000:      69.6797,
		Magnitude:     8.4,
		AngularSize:   11.2,
		Constellation: "UMa",
		Description:   "Starburst irregular galaxy interacting gravitationally with M81",
		CatalogSource: "messier",
	},
	// --- insert remaining objects in M39 block ---
	{
		Name:          "",
		CatalogID:     "M39",
		AlternateIDs:  []string{"NGC 7092"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       21.5283,
		DecJ2000:      48.4333,
		Magnitude:     4.6,
		AngularSize:   32.0,
		Constellation: "Cyg",
		Description:   "Large, scattered open cluster; about 30 bright stars",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M40",
		AlternateIDs:  []string{"WNC 4"},
		Type:          ObjectTypeDoubleStar,
		RAJ2000:       12.3719,
		DecJ2000:      58.0833,
		Magnitude:     8.4,
		AngularSize:   0.8,
		Constellation: "UMa",
		Description:   "Double star (Winnecke 4); listed by Messier as a possible nebula; no deep-sky object",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M41",
		AlternateIDs:  []string{"NGC 2287"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       6.7833,
		DecJ2000:      -20.7333,
		Magnitude:     4.5,
		AngularSize:   38.0,
		Constellation: "CMa",
		Description:   "Open cluster south of Sirius; ~100 stars including many red giants",
		CatalogSource: "messier",
	},
	{
		Name:          "Orion Nebula",
		CatalogID:     "M42",
		AlternateIDs:  []string{"NGC 1976"},
		Type:          ObjectTypeNebula,
		RAJ2000:       5.5883,
		DecJ2000:      -5.3900,
		Magnitude:     4.0,
		AngularSize:   85.0,
		Constellation: "Ori",
		Description:   "Closest large star-forming region; contains the Trapezium OB cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "De Mairan's Nebula",
		CatalogID:     "M43",
		AlternateIDs:  []string{"NGC 1982"},
		Type:          ObjectTypeNebula,
		RAJ2000:       5.5933,
		DecJ2000:      -5.2667,
		Magnitude:     9.0,
		AngularSize:   20.0,
		Constellation: "Ori",
		Description:   "Detached northern portion of the Orion Nebula complex",
		CatalogSource: "messier",
	},
	{
		Name:          "Beehive Cluster",
		CatalogID:     "M44",
		AlternateIDs:  []string{"NGC 2632"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       8.6708,
		DecJ2000:      19.9833,
		Magnitude:     3.7,
		AngularSize:   95.0,
		Constellation: "Cnc",
		Description:   "Praesepe; one of the nearest open clusters; ~1000 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "Pleiades",
		CatalogID:     "M45",
		AlternateIDs:  []string{},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       3.7908,
		DecJ2000:      24.1167,
		Magnitude:     1.6,
		AngularSize:   110.0,
		Constellation: "Tau",
		Description:   "Seven Sisters; nearest and most prominent open cluster; associated reflection nebulosity",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M46",
		AlternateIDs:  []string{"NGC 2437"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       7.6953,
		DecJ2000:      -14.8167,
		Magnitude:     6.1,
		AngularSize:   27.0,
		Constellation: "Pup",
		Description:   "Rich open cluster; foreground planetary nebula NGC 2438 is a line-of-sight coincidence",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M47",
		AlternateIDs:  []string{"NGC 2422"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       7.6097,
		DecJ2000:      -14.5000,
		Magnitude:     4.4,
		AngularSize:   30.0,
		Constellation: "Pup",
		Description:   "Bright, loose open cluster west of M46; ~50 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M48",
		AlternateIDs:  []string{"NGC 2548"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       8.2286,
		DecJ2000:      -5.8000,
		Magnitude:     5.5,
		AngularSize:   54.0,
		Constellation: "Hya",
		Description:   "Large open cluster of about 80 stars; long considered a 'missing' Messier",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M50",
		AlternateIDs:  []string{"NGC 2323"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       7.0425,
		DecJ2000:      -8.3500,
		Magnitude:     6.3,
		AngularSize:   16.0,
		Constellation: "Mon",
		Description:   "Heart-shaped open cluster of ~200 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "Whirlpool Galaxy",
		CatalogID:     "M51",
		AlternateIDs:  []string{"NGC 5194"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       13.4978,
		DecJ2000:      47.1952,
		Magnitude:     8.4,
		AngularSize:   11.2,
		Constellation: "CVn",
		Description:   "Grand design spiral interacting with companion NGC 5195; first galaxy with visible spiral structure",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M52",
		AlternateIDs:  []string{"NGC 7654"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       23.4003,
		DecJ2000:      61.5833,
		Magnitude:     7.3,
		AngularSize:   13.0,
		Constellation: "Cas",
		Description:   "Rich, compact open cluster of ~200 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "Butterfly Nebula",
		CatalogID:     "M76",
		AlternateIDs:  []string{"NGC 650", "NGC 651"},
		Type:          ObjectTypePlanetaryNeb,
		RAJ2000:       1.7025,
		DecJ2000:      51.5753,
		Magnitude:     10.1,
		AngularSize:   2.7,
		Constellation: "Per",
		Description:   "Little Dumbbell Nebula; faintest Messier object; double-lobed planetary nebula",
		CatalogSource: "messier",
	},
	{
		Name:          "Spindle Galaxy",
		CatalogID:     "M102",
		AlternateIDs:  []string{"NGC 5866"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       15.1072,
		DecJ2000:      55.7658,
		Magnitude:     9.9,
		AngularSize:   6.5,
		Constellation: "Dra",
		Description:   "Edge-on lenticular galaxy with prominent dust lane; identity disputed historically",
		CatalogSource: "messier",
	},
	// Fill in remaining objects in strict M-number order below.
	{
		Name:          "",
		CatalogID:     "M53",
		AlternateIDs:  []string{"NGC 5024"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       13.2150,
		DecJ2000:      18.1683,
		Magnitude:     7.7,
		AngularSize:   12.6,
		Constellation: "Com",
		Description:   "One of the more remote globular clusters at ~58,000 ly",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M54",
		AlternateIDs:  []string{"NGC 6715"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       18.9178,
		DecJ2000:      -30.4783,
		Magnitude:     7.7,
		AngularSize:   12.0,
		Constellation: "Sgr",
		Description:   "Globular cluster in the Sagittarius Dwarf Elliptical Galaxy",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M55",
		AlternateIDs:  []string{"NGC 6809"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       19.6669,
		DecJ2000:      -30.9650,
		Magnitude:     7.4,
		AngularSize:   19.0,
		Constellation: "Sgr",
		Description:   "Large, loose globular cluster with low central concentration",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M56",
		AlternateIDs:  []string{"NGC 6779"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       19.2761,
		DecJ2000:      30.1833,
		Magnitude:     8.3,
		AngularSize:   8.8,
		Constellation: "Lyr",
		Description:   "Globular cluster in Lyra; relatively faint and loose",
		CatalogSource: "messier",
	},
	{
		Name:          "Ring Nebula",
		CatalogID:     "M57",
		AlternateIDs:  []string{"NGC 6720"},
		Type:          ObjectTypePlanetaryNeb,
		RAJ2000:       18.8931,
		DecJ2000:      33.0289,
		Magnitude:     8.8,
		AngularSize:   1.4,
		Constellation: "Lyr",
		Description:   "Prototype ring-shaped planetary nebula; white dwarf central star",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M58",
		AlternateIDs:  []string{"NGC 4579"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.6283,
		DecJ2000:      11.8183,
		Magnitude:     9.7,
		AngularSize:   5.9,
		Constellation: "Vir",
		Description:   "Barred spiral galaxy; one of the brightest in the Virgo Cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M59",
		AlternateIDs:  []string{"NGC 4621"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.7006,
		DecJ2000:      11.6467,
		Magnitude:     9.6,
		AngularSize:   5.4,
		Constellation: "Vir",
		Description:   "Elliptical galaxy in the Virgo Cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M60",
		AlternateIDs:  []string{"NGC 4649"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.7272,
		DecJ2000:      11.5528,
		Magnitude:     8.8,
		AngularSize:   7.4,
		Constellation: "Vir",
		Description:   "Giant elliptical; interacting pair with NGC 4647; harbors a massive black hole",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M61",
		AlternateIDs:  []string{"NGC 4303"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.3647,
		DecJ2000:      4.4733,
		Magnitude:     9.7,
		AngularSize:   6.5,
		Constellation: "Vir",
		Description:   "Barred spiral galaxy on the southern outskirts of the Virgo Cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M62",
		AlternateIDs:  []string{"NGC 6266"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       17.0211,
		DecJ2000:      -30.1133,
		Magnitude:     6.5,
		AngularSize:   15.0,
		Constellation: "Oph",
		Description:   "Asymmetric globular cluster with offset core; near the galactic center",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M63",
		AlternateIDs:  []string{"NGC 5055"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       13.2636,
		DecJ2000:      42.0292,
		Magnitude:     8.6,
		AngularSize:   12.6,
		Constellation: "CVn",
		Description:   "Sunflower Galaxy; flocculent spiral with patchy, multi-arm structure",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M64",
		AlternateIDs:  []string{"NGC 4826"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.9433,
		DecJ2000:      21.6825,
		Magnitude:     8.5,
		AngularSize:   10.0,
		Constellation: "Com",
		Description:   "Black Eye Galaxy; striking dust lane absorbs light on one side of nucleus",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M65",
		AlternateIDs:  []string{"NGC 3623"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       11.3131,
		DecJ2000:      13.0925,
		Magnitude:     9.3,
		AngularSize:   8.7,
		Constellation: "Leo",
		Description:   "Intermediate spiral galaxy; member of the Leo Triplet",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M66",
		AlternateIDs:  []string{"NGC 3627"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       11.3358,
		DecJ2000:      12.9917,
		Magnitude:     8.9,
		AngularSize:   9.1,
		Constellation: "Leo",
		Description:   "Barred spiral galaxy; brightest of the Leo Triplet; gravitationally disturbed",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M67",
		AlternateIDs:  []string{"NGC 2682"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       8.8561,
		DecJ2000:      11.8000,
		Magnitude:     6.1,
		AngularSize:   30.0,
		Constellation: "Cnc",
		Description:   "One of the oldest known open clusters (~4 Gyr); ~500 solar-type stars",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M68",
		AlternateIDs:  []string{"NGC 4590"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       12.6597,
		DecJ2000:      -26.7450,
		Magnitude:     8.3,
		AngularSize:   12.0,
		Constellation: "Hya",
		Description:   "Metal-poor globular cluster; loose central concentration",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M69",
		AlternateIDs:  []string{"NGC 6637"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       18.5231,
		DecJ2000:      -32.3481,
		Magnitude:     7.7,
		AngularSize:   9.8,
		Constellation: "Sgr",
		Description:   "Compact globular near the galactic center; metal-rich",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M70",
		AlternateIDs:  []string{"NGC 6681"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       18.7197,
		DecJ2000:      -32.2917,
		Magnitude:     8.1,
		AngularSize:   8.0,
		Constellation: "Sgr",
		Description:   "Compact globular cluster near the galactic center",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M71",
		AlternateIDs:  []string{"NGC 6838"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       19.8964,
		DecJ2000:      18.7792,
		Magnitude:     8.4,
		AngularSize:   7.2,
		Constellation: "Sge",
		Description:   "Loose, low-concentration globular cluster; once classified as a dense open cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M72",
		AlternateIDs:  []string{"NGC 6981"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       20.8906,
		DecJ2000:      -12.5369,
		Magnitude:     9.3,
		AngularSize:   6.6,
		Constellation: "Aqr",
		Description:   "Remote, sparse globular cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M73",
		AlternateIDs:  []string{"NGC 6994"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       20.9881,
		DecJ2000:      -12.6333,
		Magnitude:     9.0,
		AngularSize:   2.8,
		Constellation: "Aqr",
		Description:   "Asterism of four stars; probably not a true cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M74",
		AlternateIDs:  []string{"NGC 628"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       1.6119,
		DecJ2000:      15.7836,
		Magnitude:     9.4,
		AngularSize:   10.5,
		Constellation: "Psc",
		Description:   "Face-on grand design spiral galaxy; low surface brightness",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M75",
		AlternateIDs:  []string{"NGC 6864"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       20.1014,
		DecJ2000:      -21.9217,
		Magnitude:     8.6,
		AngularSize:   6.8,
		Constellation: "Sgr",
		Description:   "Highly concentrated globular cluster; one of the more remote in the catalog",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M77",
		AlternateIDs:  []string{"NGC 1068"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       2.7114,
		DecJ2000:      -0.0133,
		Magnitude:     8.9,
		AngularSize:   7.1,
		Constellation: "Cet",
		Description:   "Seyfert 2 active galactic nucleus; brightest Seyfert galaxy in the sky",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M78",
		AlternateIDs:  []string{"NGC 2068"},
		Type:          ObjectTypeNebula,
		RAJ2000:       5.7792,
		DecJ2000:      0.0717,
		Magnitude:     8.3,
		AngularSize:   8.0,
		Constellation: "Ori",
		Description:   "Brightest reflection nebula in Messier's catalog; part of Orion molecular cloud",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M79",
		AlternateIDs:  []string{"NGC 1904"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       5.4033,
		DecJ2000:      -24.5233,
		Magnitude:     8.0,
		AngularSize:   9.6,
		Constellation: "Lep",
		Description:   "Compact globular cluster; unusual winter-sky location",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M80",
		AlternateIDs:  []string{"NGC 6093"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       16.2839,
		DecJ2000:      -22.9761,
		Magnitude:     7.3,
		AngularSize:   10.0,
		Constellation: "Sco",
		Description:   "Dense, highly concentrated globular cluster; site of a recorded nova in 1860",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M83",
		AlternateIDs:  []string{"NGC 5236"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       13.6169,
		DecJ2000:      -29.8658,
		Magnitude:     7.6,
		AngularSize:   13.5,
		Constellation: "Hya",
		Description:   "Southern Pinwheel Galaxy; face-on barred spiral with very active star formation",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M84",
		AlternateIDs:  []string{"NGC 4374"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.4200,
		DecJ2000:      12.8869,
		Magnitude:     9.1,
		AngularSize:   6.5,
		Constellation: "Vir",
		Description:   "Lenticular galaxy in Markarian's Chain in the Virgo Cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M85",
		AlternateIDs:  []string{"NGC 4382"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.4233,
		DecJ2000:      18.1908,
		Magnitude:     9.1,
		AngularSize:   7.1,
		Constellation: "Com",
		Description:   "Lenticular galaxy; northernmost bright member of the Virgo Cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M86",
		AlternateIDs:  []string{"NGC 4406"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.4369,
		DecJ2000:      12.9461,
		Magnitude:     8.9,
		AngularSize:   8.9,
		Constellation: "Vir",
		Description:   "Lenticular galaxy in the Virgo Cluster; approaching the Milky Way (blueshifted)",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M87",
		AlternateIDs:  []string{"NGC 4486"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.5136,
		DecJ2000:      12.3911,
		Magnitude:     8.6,
		AngularSize:   8.3,
		Constellation: "Vir",
		Description:   "Giant elliptical; first image of a black hole event horizon (2019); prominent relativistic jet",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M88",
		AlternateIDs:  []string{"NGC 4501"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.5322,
		DecJ2000:      14.4200,
		Magnitude:     9.6,
		AngularSize:   6.9,
		Constellation: "Com",
		Description:   "Barred spiral in the Virgo Cluster; nearly edge-on",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M89",
		AlternateIDs:  []string{"NGC 4552"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.5939,
		DecJ2000:      12.5561,
		Magnitude:     9.8,
		AngularSize:   5.1,
		Constellation: "Vir",
		Description:   "Elliptical galaxy in the Virgo Cluster; nearly perfectly round in appearance",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M90",
		AlternateIDs:  []string{"NGC 4569"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.6136,
		DecJ2000:      13.1628,
		Magnitude:     9.5,
		AngularSize:   9.5,
		Constellation: "Vir",
		Description:   "Spiral galaxy infalling into the Virgo Cluster; one of few galaxies with a blueshift",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M91",
		AlternateIDs:  []string{"NGC 4548"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.5919,
		DecJ2000:      14.4958,
		Magnitude:     10.2,
		AngularSize:   5.4,
		Constellation: "Com",
		Description:   "Barred spiral galaxy in the Virgo Cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M92",
		AlternateIDs:  []string{"NGC 6341"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       17.2853,
		DecJ2000:      43.1358,
		Magnitude:     6.5,
		AngularSize:   14.0,
		Constellation: "Her",
		Description:   "Bright globular cluster in Hercules; only slightly less spectacular than M13",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M93",
		AlternateIDs:  []string{"NGC 2447"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       7.7417,
		DecJ2000:      -23.8667,
		Magnitude:     6.2,
		AngularSize:   22.0,
		Constellation: "Pup",
		Description:   "Butterfly-shaped open cluster of about 80 stars",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M94",
		AlternateIDs:  []string{"NGC 4736"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.8483,
		DecJ2000:      41.1203,
		Magnitude:     8.2,
		AngularSize:   11.2,
		Constellation: "CVn",
		Description:   "Spiral galaxy with bright inner ring and active starburst ring",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M95",
		AlternateIDs:  []string{"NGC 3351"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       10.7031,
		DecJ2000:      11.7033,
		Magnitude:     9.7,
		AngularSize:   7.4,
		Constellation: "Leo",
		Description:   "Barred spiral galaxy with a prominent ring around the bar",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M96",
		AlternateIDs:  []string{"NGC 3368"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       10.7794,
		DecJ2000:      11.8197,
		Magnitude:     9.2,
		AngularSize:   7.8,
		Constellation: "Leo",
		Description:   "Brightest member of the Leo I Group; asymmetric intermediate spiral",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M97",
		AlternateIDs:  []string{"NGC 3587"},
		Type:          ObjectTypePlanetaryNeb,
		RAJ2000:       11.2472,
		DecJ2000:      55.0192,
		Magnitude:     9.9,
		AngularSize:   3.4,
		Constellation: "UMa",
		Description:   "Owl Nebula; large, faint planetary nebula; two dark eye-like depressions",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M98",
		AlternateIDs:  []string{"NGC 4192"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.2311,
		DecJ2000:      14.9003,
		Magnitude:     10.1,
		AngularSize:   9.8,
		Constellation: "Com",
		Description:   "Spiral galaxy approaching the Milky Way; one of few blue-shifted galaxies",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M99",
		AlternateIDs:  []string{"NGC 4254"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.3128,
		DecJ2000:      14.4169,
		Magnitude:     9.9,
		AngularSize:   5.4,
		Constellation: "Com",
		Description:   "Nearly face-on spiral; one of the first objects recognized to have a spiral structure",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M100",
		AlternateIDs:  []string{"NGC 4321"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.3831,
		DecJ2000:      15.8222,
		Magnitude:     9.3,
		AngularSize:   7.4,
		Constellation: "Com",
		Description:   "Grand design spiral galaxy; one of the brightest in the Virgo Cluster",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M101",
		AlternateIDs:  []string{"NGC 5457"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       14.0533,
		DecJ2000:      54.3492,
		Magnitude:     7.9,
		AngularSize:   28.8,
		Constellation: "UMa",
		Description:   "Pinwheel Galaxy; nearly perfect face-on spiral; asymmetric arms with many HII regions",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M103",
		AlternateIDs:  []string{"NGC 581"},
		Type:          ObjectTypeOpenCluster,
		RAJ2000:       1.5567,
		DecJ2000:      60.6500,
		Magnitude:     7.4,
		AngularSize:   6.0,
		Constellation: "Cas",
		Description:   "Open cluster of about 40 stars; last object in the original Messier list",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M104",
		AlternateIDs:  []string{"NGC 4594"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.6664,
		DecJ2000:      -11.6231,
		Magnitude:     8.0,
		AngularSize:   8.9,
		Constellation: "Vir",
		Description:   "Sombrero Galaxy; edge-on spiral with prominent dust lane and large bulge",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M105",
		AlternateIDs:  []string{"NGC 3379"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       10.7967,
		DecJ2000:      12.5817,
		Magnitude:     9.3,
		AngularSize:   5.4,
		Constellation: "Leo",
		Description:   "Elliptical galaxy; brightest elliptical in the Leo I Group",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M106",
		AlternateIDs:  []string{"NGC 4258"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       12.3161,
		DecJ2000:      47.3036,
		Magnitude:     8.4,
		AngularSize:   18.6,
		Constellation: "CVn",
		Description:   "Seyfert 2 spiral galaxy; contains a well-studied water megamaser",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M107",
		AlternateIDs:  []string{"NGC 6171"},
		Type:          ObjectTypeGlobularClust,
		RAJ2000:       16.5419,
		DecJ2000:      -13.0533,
		Magnitude:     8.9,
		AngularSize:   13.0,
		Constellation: "Oph",
		Description:   "Loose globular cluster with patchy appearance from dark nebulae",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M108",
		AlternateIDs:  []string{"NGC 3556"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       11.1917,
		DecJ2000:      55.6739,
		Magnitude:     10.0,
		AngularSize:   8.7,
		Constellation: "UMa",
		Description:   "Edge-on barred spiral galaxy near M97; mottled, dusty appearance",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M109",
		AlternateIDs:  []string{"NGC 3992"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       11.9578,
		DecJ2000:      53.3747,
		Magnitude:     9.8,
		AngularSize:   7.6,
		Constellation: "UMa",
		Description:   "Barred spiral galaxy near Gamma UMa (Phecda)",
		CatalogSource: "messier",
	},
	{
		Name:          "",
		CatalogID:     "M110",
		AlternateIDs:  []string{"NGC 205"},
		Type:          ObjectTypeGalaxy,
		RAJ2000:       0.6728,
		DecJ2000:      41.6853,
		Magnitude:     8.7,
		AngularSize:   21.9,
		Constellation: "And",
		Description:   "Dwarf elliptical satellite galaxy of M31; contains star-forming regions unusual for its type",
		CatalogSource: "messier",
	},
}
